# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# #food groups
FoodGroup.create(:name => "Lacteos", :color => "#cfd8dc")
FoodGroup.create(:name => "Hortalizas", :color => "#8bc34a")
FoodGroup.create(:name => "Frutas", :color => "#ffd54f")
FoodGroup.create(:name => "Harinas", :color => "#827717")
FoodGroup.create(:name => "Leguminosas", :color => "#9e9e9e")
FoodGroup.create(:name => "Carnes", :color => "#c62828")
FoodGroup.create(:name => "Grasas", :color => "#795548")
FoodGroup.create(:name => "Azucar", :color => "#90a4ae")
FoodGroup.create(:name => "Bebidas gaseosas", :color => "#ffeb3b")
FoodGroup.create(:name => "Bebidas alcoholicas", :color => "#e0e0e0")
FoodGroup.create(:name => "Extras", :color => "#ffffff")

# #food types
FoodType.create(:food_group_id => 1, :name => "Entera", :kcal => 135, :proteins => 8, :fats => 7,:carbs => 10)
FoodType.create(:food_group_id => 1, :name => "Semidescremada", :kcal => 120, :proteins => 8, :fats => 5,:carbs => 10)
FoodType.create(:food_group_id => 1, :name => "Descremada", :kcal => 80, :proteins => 8, :fats => 1,:carbs => 10)
FoodType.create(:food_group_id => 2, :name => "Hortalizas", :kcal => 35, :proteins => 2, :fats => 0,:carbs => 7)
FoodType.create(:food_group_id => 2, :name => "Hortalizas sin aporte", :kcal => 0, :proteins => 0, :fats => 0,:carbs => 0)
FoodType.create(:food_group_id => 3, :name => "Frutas", :kcal => 60, :proteins => 0, :fats => 0,:carbs => 15)
FoodType.create(:food_group_id => 4, :name => "Harinas", :kcal => 70, :proteins => 2, :fats => 0,:carbs => 15)
FoodType.create(:food_group_id => 5, :name => "Leguminosas y mezclas vegetales", :kcal => 180, :proteins => 3, :fats => 0,:carbs => 32)
FoodType.create(:food_group_id => 6, :name => "Muy magra", :kcal => 100, :proteins => 21, :fats => 2,:carbs => 0)
FoodType.create(:food_group_id => 6, :name => "Magra", :kcal => 150, :proteins => 22, :fats => 7,:carbs => 0)
FoodType.create(:food_group_id => 6, :name => "Semigorda", :kcal => 230, :proteins => 19, :fats => 17,:carbs => 0)
FoodType.create(:food_group_id => 6, :name => "Gorda", :kcal => 290, :proteins => 16, :fats => 25,:carbs => 0)
FoodType.create(:food_group_id => 7, :name => "Grasas", :kcal => 45, :proteins => 0, :fats => 5,:carbs => 0)
FoodType.create(:food_group_id => 8, :name => "Azucar", :kcal => 60, :proteins => 0, :fats => 0,:carbs => 15)
FoodType.create(:food_group_id => 9, :name => "Bebidas gaseosas", :kcal => 80, :proteins => 0, :fats => 0,:carbs => 20)
FoodType.create(:food_group_id => 10, :name => "Bebidas alcoholicas", :kcal => 140, :proteins => 0, :fats => 0,:carbs => 0)
FoodType.create(:food_group_id => 11, :name => "Extras", :kcal => 0, :proteins => 0, :fats => 0,:carbs => 0)

#foods
Food.create(:food_type_id => 1, :name => 'LECHE PASTEURIZADA', :quantity => 240, :home_quantity => '1 POCILLO')
Food.create(:food_type_id => 1, :name => 'LECHE EN POLVO ENTERA', :quantity => 30, :home_quantity => '4 CUCHARADAS')
Food.create(:food_type_id => 1, :name => 'YOGURT NATURAL CON DULCE', :quantity => 200, :home_quantity => '1 POCILLO BAJITO')
Food.create(:food_type_id => 1, :name => 'ALPINITO', :quantity => 45, :home_quantity => '1 VASO')

Food.create(:food_type_id => 2, :name => 'LECHE BAJA EN GRASA 2%', :quantity => 240, :home_quantity => '1 POCILLO')
Food.create(:food_type_id => 2, :name => 'YOGURT DIETETICO FITNESSE', :quantity => 360, :home_quantity => '2 VASITOS')

Food.create(:food_type_id => 3, :name => 'LECHE DESCREMADA', :quantity => 240, :home_quantity => '1 POCILLO')
Food.create(:food_type_id => 3, :name => 'YOGURT NATURAL BAJO EN GRASA', :quantity => 200, :home_quantity => '1 POCILLO BAJITO')
Food.create(:food_type_id => 3, :name => 'YOGURT CON FRUTAS BAJO EN GRASA', :quantity => 180, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 3, :name => 'KUMIS CON DULCE', :quantity => 120, :home_quantity => '1/2 POCILLO')

Food.create(:food_type_id => 4, :name => 'ARVEJA VERDE', :quantity => 30, :home_quantity => '2 CUCHARADAS')
Food.create(:food_type_id => 4, :name => 'AUYAMA', :quantity => 90, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 4, :name => 'CEBOLLA PUERRO', :quantity => 58, :home_quantity => 'TALLO')
Food.create(:food_type_id => 4, :name => 'COLIFLOR', :quantity => 121, :home_quantity => 'POCILLO O 5 RAMITOS MEDIANOS')
Food.create(:food_type_id => 4, :name => 'CUBIOS', :quantity => 60, :home_quantity => 'UNIDAD PEQUEÑA')
Food.create(:food_type_id => 4, :name => 'FRIJOL VERDE', :quantity => 23, :home_quantity => '1 CUCHARADA SOPERA RAS ')
Food.create(:food_type_id => 4, :name => 'HABAS VERDES', :quantity => 27, :home_quantity => '10 UNIDADES')
Food.create(:food_type_id => 4, :name => 'PASTA DE TOMATE', :quantity => 47, :home_quantity => '7 UNIDADES')
Food.create(:food_type_id => 4, :name => 'PALMITOS', :quantity => 61, :home_quantity => '3 CUCHARADAS SOPERAS')
Food.create(:food_type_id => 4, :name => 'REMOLACHA', :quantity => 83, :home_quantity => '1/2 POCILLO O 1 UNIDAD MEDIANA')
Food.create(:food_type_id => 4, :name => 'REPOLLITAS DE BRUSLAS', :quantity => 85, :home_quantity => '10 UNIDADES')
Food.create(:food_type_id => 4, :name => 'SALSA DE TOMATE', :quantity => 36, :home_quantity => '2 CUCHARADAS SOPERAS RASAS')
Food.create(:food_type_id => 4, :name => 'ZANAHORIA', :quantity => 97, :home_quantity => '1 UNIDAD MEDIANA ')

Food.create(:food_type_id => 5, :name => 'ACELGA', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'ALCACHFA', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'APIO', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'BERENJENA', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'BROCOLI', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'CALABAZA', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'ESPINACA', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'GUASCAS', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'HABICHUELAS', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'LECHUGA', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'PEPINO COMUN', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'PEPINO', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'RABANOS', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'REPOLLO', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 5, :name => 'TALLAS O COL', :quantity => 0, :home_quantity => '0')

Food.create(:food_type_id => 6, :name => 'ANON', :quantity => 60, :home_quantity => '1 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 6, :name => 'BANANO COMUN', :quantity => 70, :home_quantity => '1/2 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 6, :name => 'BANANO BOCADILLO', :quantity => 56, :home_quantity => '1 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 6, :name => 'BREVA VERDE', :quantity => 150, :home_quantity => '5 UNIDADES PEQUEÑAS')
Food.create(:food_type_id => 6, :name => 'CEREZAS', :quantity => 70, :home_quantity => '18 UNIDADES')
Food.create(:food_type_id => 6, :name => 'CHIRIMOYA', :quantity => 83, :home_quantity => '1/2 UNIDAD')
Food.create(:food_type_id => 6, :name => 'CHONTADURO', :quantity => 22, :home_quantity => '1 UNIDAD GRANDE')
Food.create(:food_type_id => 6, :name => 'CIRUELA COMUN', :quantity => 75, :home_quantity => '12 UNIDADES PEQUEÑAS')
Food.create(:food_type_id => 6, :name => 'CIRUELA PASAS', :quantity => 25, :home_quantity => '3 UNIDADES')
Food.create(:food_type_id => 6, :name => 'CURUBA', :quantity => 380, :home_quantity => '9 UNIDADES')
Food.create(:food_type_id => 6, :name => 'DURAZNO AMARILLO', :quantity => 125, :home_quantity => 'UNIDADES MEDIANAS')
Food.create(:food_type_id => 6, :name => 'DURAZNO ENLATADO', :quantity => 110, :home_quantity => '2 RODAJAS')
Food.create(:food_type_id => 6, :name => 'FEIJOA', :quantity => 125, :home_quantity => '2 UNIDADES MEDIANAS')
Food.create(:food_type_id => 6, :name => 'FRESAS', :quantity => 190, :home_quantity => '13 UNIDADES')
Food.create(:food_type_id => 6, :name => 'GUANABANA', :quantity => 120, :home_quantity => '6 CUCHARADAS SOPERAS')
Food.create(:food_type_id => 6, :name => 'GUAYABA', :quantity => 165, :home_quantity => '3 UNIDADES')
Food.create(:food_type_id => 6, :name => 'GRANADILLA', :quantity => 125, :home_quantity => '4 UNIDADES')
Food.create(:food_type_id => 6, :name => 'HIGOS', :quantity => 180, :home_quantity => '3 UNIDADES')
Food.create(:food_type_id => 6, :name => 'JUGO DE NARANJA', :quantity => 240, :home_quantity => '1 pocillo')
Food.create(:food_type_id => 6, :name => 'JUGO DE PIÑA', :quantity => 120, :home_quantity => '1/2 POCILLO')
Food.create(:food_type_id => 6, :name => 'JUGO DE LULO', :quantity => 240, :home_quantity => '1 POCILLO')
Food.create(:food_type_id => 6, :name => 'MANDARINA', :quantity => 160, :home_quantity => '2 UNIDADES ')
Food.create(:food_type_id => 6, :name => 'MANGO', :quantity => 100, :home_quantity => '1 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 6, :name => 'MAMONCILLO', :quantity => 80, :home_quantity => '23 UNIDADES')
Food.create(:food_type_id => 6, :name => 'MANZANA', :quantity => 110, :home_quantity => '1 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 6, :name => 'MARACUYA', :quantity => 125, :home_quantity => '2 UNIDADES')
Food.create(:food_type_id => 6, :name => 'MELON', :quantity => 180, :home_quantity => '1 1/2 POCILLOS')
Food.create(:food_type_id => 6, :name => 'MORAS', :quantity => 250, :home_quantity => '1 1/2 POCILLOS ')
Food.create(:food_type_id => 6, :name => 'NARANJA', :quantity => 170, :home_quantity => '1 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 6, :name => 'PAPAYA', :quantity => 200, :home_quantity => '1 POCILLO')
Food.create(:food_type_id => 6, :name => 'PAPAYUELA', :quantity => 380, :home_quantity => '6 UNIDADES PEQUEÑAS')
Food.create(:food_type_id => 6, :name => 'PATILLA O SANDIA', :quantity => 180, :home_quantity => '1 1/2 POCILLOS')
Food.create(:food_type_id => 6, :name => 'PERA', :quantity => 190, :home_quantity => '1 UNIDAD')
Food.create(:food_type_id => 6, :name => 'PIÑA', :quantity => 120, :home_quantity => '1 TAJADA DELGADA')
Food.create(:food_type_id => 6, :name => 'PITAHAYA', :quantity => 120, :home_quantity => '2 UNIDADES PEQUEÑAS')
Food.create(:food_type_id => 6, :name => 'POMARROSA', :quantity => 100, :home_quantity => '7 UNIDADES')
Food.create(:food_type_id => 6, :name => 'TAMARINDO', :quantity => 22, :home_quantity => '1 1/2 CUCHARADA RAS')
Food.create(:food_type_id => 6, :name => 'TORONJA', :quantity => 200, :home_quantity => '1 UNIDAD')
Food.create(:food_type_id => 6, :name => 'TOMATE DE ARBOL', :quantity => 200, :home_quantity => '3 UNIDADES MEDIANAS')
Food.create(:food_type_id => 6, :name => 'UCHUVAS', :quantity => 123, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 6, :name => 'UVAS', :quantity => 185, :home_quantity => '20 UNIDADES ')
Food.create(:food_type_id => 6, :name => 'UVAS PASAS', :quantity => 20, :home_quantity => '3 CUCHARADITAS')
Food.create(:food_type_id => 6, :name => 'ZAPOTE', :quantity => 123, :home_quantity => '1 UNIDAD')

Food.create(:food_type_id => 7, :name => 'ARROZ BLANCO', :quantity => 20, :home_quantity => '1/3POCILLO')
Food.create(:food_type_id => 7, :name => 'AVENA', :quantity => 20, :home_quantity => '3CUCHARADA RAS')
Food.create(:food_type_id => 7, :name => 'CEBADA PERLADA', :quantity => 20, :home_quantity => '2 CUCHARADA RAS')
Food.create(:food_type_id => 7, :name => 'CUCHUCO DE TRIGO', :quantity => 21, :home_quantity => '2 CUCHARADA RAS')
Food.create(:food_type_id => 7, :name => 'HARINA DE MAIZ', :quantity => 21, :home_quantity => '2 CUCHARADA RAS')
Food.create(:food_type_id => 7, :name => 'HARINA DE TRIGO', :quantity => 20, :home_quantity => '3 CUCHARADA RAS')
Food.create(:food_type_id => 7, :name => 'MALZENA', :quantity => 20, :home_quantity => '3 CUCHARADA RAS')
Food.create(:food_type_id => 7, :name => 'MAIZMUTE', :quantity => 71, :home_quantity => '4 CUCHARADA RAS')
Food.create(:food_type_id => 7, :name => 'MAIZ PIRA', :quantity => 21, :home_quantity => '1 POCILLO PREPARADO ')
Food.create(:food_type_id => 7, :name => 'MAIZ TIERNO', :quantity => 51, :home_quantity => '3 CUCHARADAS RAS')
Food.create(:food_type_id => 7, :name => 'SOPAS DE HARINAS', :quantity => 120, :home_quantity => '1/2 PLATO')
Food.create(:food_type_id => 7, :name => 'ALMOHABANA', :quantity => 24, :home_quantity => 'PLATO')
Food.create(:food_type_id => 7, :name => 'AREPA DE MAIZ AMARILLO', :quantity => 50, :home_quantity => '1/2 UNIDAD MEDIANA')
Food.create(:food_type_id => 7, :name => 'AREPA PLANA DELGADA', :quantity => 38, :home_quantity => '1/2 UNIDAD MEDIANA')
Food.create(:food_type_id => 7, :name => 'AREPA PLANA SEMI GRUEGA', :quantity => 48, :home_quantity => '1/2 UNIDAD MEDIANA')
Food.create(:food_type_id => 7, :name => 'AREPA REDONDA', :quantity => 40, :home_quantity => '1/2 UNIDAD')
Food.create(:food_type_id => 7, :name => 'BROWNIE', :quantity => 20, :home_quantity => '1/4 UNIDAD')
Food.create(:food_type_id => 7, :name => 'BUÑUELO', :quantity => 20, :home_quantity => '1/4 UNIDAD GRANDE')
Food.create(:food_type_id => 7, :name => 'CEREAL ALL BRAN', :quantity => 20, :home_quantity => '1/4 POCILLO O 4 CUCHARADAS')
Food.create(:food_type_id => 7, :name => 'CORN FLAKES', :quantity => 19, :home_quantity => '1/2 POCILLO ')
Food.create(:food_type_id => 7, :name => 'CEREAL FIBER 1', :quantity => 40, :home_quantity => '1 POCILLO')
Food.create(:food_type_id => 7, :name => 'DONUT SIN RELLENO NI CUBIERTA', :quantity => 20, :home_quantity => '1/2 UNIDAD')
Food.create(:food_type_id => 7, :name => 'EMPANADAS DE GUISO', :quantity => 26, :home_quantity => '1/2 UNIDAD')
Food.create(:food_type_id => 7, :name => 'ENVUELTO DE MAZORCA', :quantity => 50, :home_quantity => '1/2 UNIDAD MEDIANA')

Food.create(:food_type_id => 7, :name => 'DUX NOEL', :quantity => 16, :home_quantity => '5 UNIDADES')
Food.create(:food_type_id => 7, :name => 'RICAS', :quantity => 16, :home_quantity => '7 UNIDADES')
Food.create(:food_type_id => 7, :name => 'SALTIN NOEL', :quantity => 16, :home_quantity => '5 UNIDADES')
Food.create(:food_type_id => 7, :name => 'CAN CAN', :quantity => 17, :home_quantity => '2 UNIDADES')
Food.create(:food_type_id => 7, :name => 'CARMELITAS', :quantity => 17, :home_quantity => '3 UNIDADES')
Food.create(:food_type_id => 7, :name => 'DE FIBRA Y MIEL', :quantity => 17, :home_quantity => '1/2 PAQUETE')
Food.create(:food_type_id => 7, :name => 'TIPO SANDWICH', :quantity => 17, :home_quantity => '2 UNIDADES')
Food.create(:food_type_id => 7, :name => 'WAFFER', :quantity => 17, :home_quantity => '3 UNIDADES')
Food.create(:food_type_id => 7, :name => 'HOJALDRE', :quantity => 19, :home_quantity => '1/4 UNIDAD MEDIANA')
Food.create(:food_type_id => 7, :name => 'MANTECADA', :quantity => 18, :home_quantity => '1/2 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 7, :name => 'MEZCLA PARA PANCAKES', :quantity => 21, :home_quantity => '3 CUCHARADAS RAS')
Food.create(:food_type_id => 7, :name => 'MOJICON', :quantity => 23, :home_quantity => '1/2 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 7, :name => 'PAN BLANCO', :quantity => 21, :home_quantity => '1 TAJADA DELGADA')
Food.create(:food_type_id => 7, :name => 'PAN HAMBURGUESA', :quantity => 21, :home_quantity => '1/3 UNIDAD')

Food.create(:food_type_id => 7, :name => 'ARRACACHA', :quantity => 75, :home_quantity => '1/2 UNIDAD')
Food.create(:food_type_id => 7, :name => 'BATATA', :quantity => 79, :home_quantity => '1/2 UNIDAD')
Food.create(:food_type_id => 7, :name => 'ÑAME', :quantity => 67, :home_quantity => '2 ASTILLAS')
Food.create(:food_type_id => 7, :name => 'PAPA COMUN CON CASCARA', :quantity => 83, :home_quantity => '1 UNIDAD MEDIANA ')
Food.create(:food_type_id => 7, :name => 'PAPA COMUN SIN CASCARA', :quantity => 77, :home_quantity => '1 UNIDAD CASERA ')
Food.create(:food_type_id => 7, :name => 'PAPA CRIOLLA', :quantity => 84, :home_quantity => '3 UNIDADES PEQUEÑAS')
Food.create(:food_type_id => 7, :name => 'PLATANO COLI Y GUINEO', :quantity => 62, :home_quantity => '1 UNIDAD')
Food.create(:food_type_id => 7, :name => 'PLATANO HARTON', :quantity => 50, :home_quantity => '1/4 UNIDAD')
Food.create(:food_type_id => 7, :name => 'PLATANO POPOCHO', :quantity => 66, :home_quantity => '3/4 UNIDAD ')
Food.create(:food_type_id => 7, :name => 'YUCA', :quantity => 48, :home_quantity => '1 ASTILLA')

Food.create(:food_type_id => 8, :name => 'ARVEJA SECA', :quantity => 60, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 8, :name => 'BIENESTARINA', :quantity => 56, :home_quantity => '10 CUCHARADAS ')
Food.create(:food_type_id => 8, :name => 'CARVE', :quantity => 54, :home_quantity => '1 1/4 POCILLO')
Food.create(:food_type_id => 8, :name => 'COLOMBIHARINA', :quantity => 55, :home_quantity => '10 CUCHARADAS RASAS')
Food.create(:food_type_id => 8, :name => 'FRIJOL BLANCO', :quantity => 60, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 8, :name => 'FRIJOL ROJO', :quantity => 60, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 8, :name => 'GARBANZO', :quantity => 53, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 8, :name => 'HABAS SECAS', :quantity => 61, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 8, :name => 'LENTEJAS', :quantity => 57, :home_quantity => '3/4 POCILLO')

Food.create(:food_type_id => 9, :name => 'JAMON TAJADO', :quantity => 84, :home_quantity => '4 TAJADAS  ')
Food.create(:food_type_id => 9, :name => 'CALLO', :quantity => 80, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 9, :name => 'JAMON DE POLLO', :quantity => 133, :home_quantity => '6 TAJADAS DELGADAS')
Food.create(:food_type_id => 9, :name => 'ATUN EN ACEITE', :quantity => 52, :home_quantity => '1 LATA')
Food.create(:food_type_id => 9, :name => 'ROBALO, PARGO ROJO', :quantity => 100, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 9, :name => 'BOCACHICO, CAPAZ, TRUCHA', :quantity => 100, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 9, :name => 'PESCADO SECO', :quantity => 30, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 9, :name => 'CAMARON', :quantity => 90, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 9, :name => 'LANGOSTA', :quantity => 110, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 9, :name => 'COTTAGE BAJO EN GRASA', :quantity => 95, :home_quantity => '3 ONZAS')
Food.create(:food_type_id => 9, :name => 'REQUESON', :quantity => 120, :home_quantity => '4 ONZAS ')

Food.create(:food_type_id => 10, :name => 'RES MAGRA TERNERA', :quantity => 100, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 10, :name => 'CERDO MAGRA', :quantity => 80, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 10, :name => 'JAMON MAGRO', :quantity => 100, :home_quantity => '4 TAJADAS  ')
Food.create(:food_type_id => 10, :name => 'HIGADO', :quantity => 110, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 10, :name => 'LENGUA', :quantity => 91, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 10, :name => 'POLLO', :quantity => 84, :home_quantity => '1/2 PECHUGA')
Food.create(:food_type_id => 10, :name => 'HUEVO', :quantity => 92, :home_quantity => '2 UNIDADES')
Food.create(:food_type_id => 10, :name => 'ATUN EN ACEITE', :quantity => 56, :home_quantity => '1/2 LATA')
Food.create(:food_type_id => 10, :name => 'BAGRE', :quantity => 81, :home_quantity => '1 PORCION PEQUEÑA')
Food.create(:food_type_id => 10, :name => 'SALMON', :quantity => 96, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 10, :name => 'SARDINAS', :quantity => 70, :home_quantity => '1 UNIDAD MEDIANA ')
Food.create(:food_type_id => 10, :name => 'RICOTA SEMIDESCREMADO', :quantity => 110, :home_quantity => '3 1/2 ONZAS')

Food.create(:food_type_id => 11, :name => 'RES SEMIGORDA', :quantity => 100, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 11, :name => 'CERDO SEMIGORDA', :quantity => 93, :home_quantity => '1 PORCION MEDIANA')
Food.create(:food_type_id => 11, :name => 'CHORIZO', :quantity => 75, :home_quantity => '1 UNIDAD GRANDE')
Food.create(:food_type_id => 11, :name => 'MORTADELA', :quantity => 74, :home_quantity => '4 TAJADAS  ')
Food.create(:food_type_id => 11, :name => 'GALLINA', :quantity => 76, :home_quantity => '1/3 DE PECHUGA')
Food.create(:food_type_id => 11, :name => 'SARDINAS EN ACEITE', :quantity => 70, :home_quantity => '1 UNIDAD')
Food.create(:food_type_id => 11, :name => 'PARMESANO', :quantity => 55, :home_quantity => ' 2 ONZAS')
Food.create(:food_type_id => 11, :name => 'QUESO PERA', :quantity => 90, :home_quantity => '3 ONZAS')

Food.create(:food_type_id => 12, :name => 'RES GORDA', :quantity => 100, :home_quantity => 'PORCION MEDIANA')
Food.create(:food_type_id => 12, :name => 'CERDO GORDA', :quantity => 100, :home_quantity => 'PORCION MEDIANA')
Food.create(:food_type_id => 12, :name => 'LONGANIZA', :quantity => 75, :home_quantity => 'UNIDAD')
Food.create(:food_type_id => 12, :name => 'SALCHICHON', :quantity => 65, :home_quantity => 'TAJADA 1 CM ANCHO')

Food.create(:food_type_id => 13, :name => 'ACEITE DE OLIVA', :quantity => 5, :home_quantity => '1 CUCHARADITA')
Food.create(:food_type_id => 13, :name => 'ACEITUNAS', :quantity => 15, :home_quantity => '10 UNIDADES')
Food.create(:food_type_id => 13, :name => 'AGUACATE', :quantity => 25, :home_quantity => '1 TAJADA PEQUEÑA 1/6 MEDIANO')
Food.create(:food_type_id => 13, :name => 'MANI', :quantity => 8, :home_quantity => '1 CUCHARADA O 29 GRANOS')
Food.create(:food_type_id => 13, :name => 'NUECES', :quantity => 7, :home_quantity => '3 UNIDADES')
Food.create(:food_type_id => 13, :name => 'ACEITE (MAIZ, GIRASOL, SOYA)', :quantity => 5, :home_quantity => '1 CUCHARADITA')
Food.create(:food_type_id => 13, :name => 'MARGARINA CON SAL', :quantity => 6, :home_quantity => '1 CUCHARADITA')
Food.create(:food_type_id => 13, :name => 'MAYONESA', :quantity => 6, :home_quantity => '1 CUCHARADITA')
Food.create(:food_type_id => 13, :name => 'COCO', :quantity => 16, :home_quantity => '1  TROZO PEQUEÑO')
Food.create(:food_type_id => 13, :name => 'CREMA DE LECHE', :quantity => 22, :home_quantity => '2 1/2CUCHARADAS')
Food.create(:food_type_id => 13, :name => 'MANTEQUILLA', :quantity => 6, :home_quantity => '1 CUCHARADITA')
Food.create(:food_type_id => 13, :name => 'TOCINETA', :quantity => 7, :home_quantity => '1 TAJADA DELGADA')

Food.create(:food_type_id => 14, :name => 'AREQUIPE', :quantity => 16, :home_quantity => '1  CUCHARADA RASA')
Food.create(:food_type_id => 14, :name => 'ARROZ CON LECHE', :quantity => 91, :home_quantity => '5 CUCHARADAS RASAS')
Food.create(:food_type_id => 14, :name => 'BOCADILLO', :quantity => 19, :home_quantity => '1/2 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 14, :name => 'CARAMELOS DUROS "CHARMS"', :quantity => 16, :home_quantity => '5 UNIDADES')
Food.create(:food_type_id => 14, :name => 'CHOCOLATINA JET', :quantity => 12, :home_quantity => '1 UNIDAD PEQUEÑA')
Food.create(:food_type_id => 14, :name => 'COMPOTA', :quantity => 65, :home_quantity => '3 CUCHARADAS RASAS')
Food.create(:food_type_id => 14, :name => 'MIEL DE ABEJAS', :quantity => 19, :home_quantity => '1 CUCHARADA RASA')
Food.create(:food_type_id => 14, :name => 'MILO', :quantity => 14, :home_quantity => '4 CUCHARADAS RASAS')
Food.create(:food_type_id => 14, :name => 'HELADO DE CREMA', :quantity => 29, :home_quantity => '3 CUCHARADAS RASAS')
Food.create(:food_type_id => 14, :name => 'HELADO DE AGUA', :quantity => 145, :home_quantity => '2 UNIDADES')
Food.create(:food_type_id => 14, :name => 'GELATINA PREPARADA', :quantity => 91, :home_quantity => '1/2 POCILLO')
Food.create(:food_type_id => 14, :name => 'AZUCAR', :quantity => 16, :home_quantity => '2 CUCHARADITAS RASAS')

Food.create(:food_type_id => 15, :name => 'COCA COLA', :quantity => 180, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 15, :name => 'GASEOSA', :quantity => 180, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 15, :name => 'GINGER ALE', :quantity => 192, :home_quantity => '3/4 POCILLO')
Food.create(:food_type_id => 15, :name => 'PONY MALTA', :quantity => 174, :home_quantity => '3/4 POCILLO')

Food.create(:food_type_id => 16, :name => 'AGUARDIENTE', :quantity => 38, :home_quantity => '1 ONZA')
Food.create(:food_type_id => 16, :name => 'BRANDY', :quantity => 57, :home_quantity => '2 ONZAS')
Food.create(:food_type_id => 16, :name => 'CERVEZA', :quantity => 300, :home_quantity => '1 BOTELLA')
Food.create(:food_type_id => 16, :name => 'RON', :quantity => 57, :home_quantity => '2 ONZAS')
Food.create(:food_type_id => 16, :name => 'VINO DULCE', :quantity => 84, :home_quantity => '3 ONZAS')
Food.create(:food_type_id => 16, :name => 'VINO SECO', :quantity => 133, :home_quantity => '4 1/2 ONZAS')
Food.create(:food_type_id => 16, :name => 'WHISKY', :quantity => 51, :home_quantity => '1 1/2 ONZA')

Food.create(:food_type_id => 17, :name => 'H20', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 17, :name => 'COCA COLA ZERO', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 17, :name => 'GELATINA LIGTH', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 17, :name => 'CHICLES TRIDENT SIN AZUCAR', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 17, :name => 'MANZANA ZERO', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 17, :name => 'SPRITE ZERO', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 17, :name => 'AGUA SABORIZADA', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 17, :name => 'CAFÉ CON SPLENDA', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 17, :name => 'MERMELADAS LIGTH ', :quantity => 0, :home_quantity => '0')
Food.create(:food_type_id => 17, :name => 'ESPECIAS', :quantity => 0, :home_quantity => '0')